project:
  type: website
  output-dir: _site

website:
  navbar:
    search: true
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Presentación"
        href: presentacion.qmd
      - text: "Proyectos"
        href: proyectos.qmd
      - text: "Portafolio"
        href: portafolio.qmd
      - text: "Conctacto"
        href: contacto.qmd


# bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: cyborg
      


